name: Meander CI

on: [push]

jobs:
  jvm-clj:

    runs-on: ubuntu-latest
    
    container:
      image:  clojure:openjdk-11-tools-deps
    
    steps:
    - uses: actions/checkout@v1
    - name: Run JVM tests
      run: clojure -A:test

  jvm-clj-and-cljs-in-cp:

    runs-on: ubuntu-latest
    
    container:
      image:  clojure:openjdk-11-tools-deps
    
    steps:
    - uses: actions/checkout@v1
    - name: Run JVM tests, with clojurescript being in the classpath
      run: clojure -A:cljs:test

  cljs:

    runs-on: ubuntu-latest
    
    container:
      image: theasp/clojurescript-nodejs:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run cljs tests
      run: clojure -A:cljs:cljs-test
